### ISSUE TITLE
Unable to download fno Bhavcopy

### ISSUE THREAD

**Issue by stockmatic** [StreamAlpha/pynse#1]
`from pynse import *
nse = Nse()
nse.bhavcopy_fno()
    `

This code is throwing error: 
`BadZipFile: File is not a zip file`

Could this be resolved?

**Comment by stockmatic** [comment]
Found out a way around, 
You just need to modify the bhavcopy_fno url to `https://www1.nseindia.com/content/historical/DERIVATIVES`

For others who are facing similar issue, you can use this:

`url = 'https://www1.nseindia.com/content/historical/DERIVATIVES/2021/JUL/fo24JUL2021bhav.csv.zip'`
```
hdr = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*,q=0.8,application/signed-exchange;v=b3;q=0.9',
       'Accept-Encoding': 'gzip, deflate, br',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'gzip, deflate, br',
       'Accept-Language': 'en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,hi;q=0.6',
       'Connection': 'keep-alive','Host':'www1.nseindia.com',
       'Cache-Control':'max-age=0',
       'Host':'www1.nseindia.com',
       'Referer':'https://www1.nseindia.com/products/content/derivatives/equities/fo.htm',
       }
```
    `session = requests.session()`
    `response = session.get(url,headers = hdr)`
    `stream = response.content`

  `  filebytes = io.BytesIO(stream)`
   ` zf = zipfile.ZipFile(filebytes)`

   ` bhavcopy = pd.read_csv(zf.open(zf.namelist()[0]))`

**Comment by AkiModi99** [comment]
> Found out a way around,
> You just need to modify the bhavcopy_fno url to `https://www1.nseindia.com/content/historical/DERIVATIVES`
> 
> For others who are facing similar issue, you can use this:
> 
> ```
> url = 'https://www1.nseindia.com/content/historical/DERIVATIVES/2021/JUL/fo23JUL2021bhav.csv.zip'
> hdr = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36',
>        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*,q=0.8,application/signed-exchange;v=b3;q=0.9',
>        'Accept-Encoding': 'gzip, deflate, br',
>        'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
>        'Accept-Encoding': 'gzip, deflate, br',
>        'Accept-Language': 'en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,hi;q=0.6',
>        'Connection': 'keep-alive','Host':'www1.nseindia.com',
>        'Cache-Control':'max-age=0',
>        'Host':'www1.nseindia.com',
>        'Referer':'https://www1.nseindia.com/products/content/derivatives/equities/fo.htm',
>        }
> 
> session = requests.session()
> response = session.get(url,headers = hdr)
> stream = response.content
> 
> filebytes = io.BytesIO(stream)
> zf = zipfile.ZipFile(filebytes)
> bhavcopy = pd.read_csv(zf.open(zf.namelist()[0]))
> ```

Hey could you please explain how to change the URL for the same, I am not able to follow. Can you provide a step-by-step guide. It would mean the world to me as I am trying to get data for a month together. Please help.
Thank you so much for the explainations.

**Comment by stockmatic** [comment]
You just need to modify the url as per the date using datetime. This is also done in this library. 

```
import datetime 

req_date = datetime.date(2021, 8 ,12)

fno_url = 'https://www1.nseindia.com/content/historical/DERIVATIVES/{year}/{month}/fo{date}bhav.csv.zip'

url = fno_url.format(date=req_date.strftime("%d%b%Y").upper(),
                                                        month=req_date.strftime(
                                                            "%b").upper(),
                                                        year=req_date.strftime("%Y"))
```
